server:
  port: 9999
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      #            ddl-auto: create-drop
      #ddl-auto: create
      ddl-auto: update
    show-sql: true
#    open-in-view: true
    properties:
      hibernate:
        format_sql: true



